Iter9
eac0de/getmetrics pull request #10
Opened 2024-07-02 14:59 UTC by eac0de

2024-07-05 02:35 UTC, capsulated requested changes
Написал комментарии, если с чем-то не согласен - ответ с аргументацией приветствуется. Также можно писать в чат подгруппы и в особо сложных вопросах 1-1

2024-07-05 02:35 UTC, capsulated commented on internal/handlers/metrics_handlers.go
> +func UpdateMetricJSONHandler(m storage.MetricsStorer) func(http.ResponseWriter, *http.Request) {
⚠️  Это очень неудобно в каждый хендлер передавать зависимость. Лучше создать один тип с методами для хендлеров. Это стандартное управления зависимостями (DI) в go:
```go
type MemStorage struct {...}
func NewMemStorgage(...) ...
func (ms *MemStorage) Create(key string, val string) error {...}
func (ms *MemStorage) Read(key string) ([]string, error) {...}

// Хендлеры
type Storage interface {
   Create(key string, val string) error
   Read(key string) ([]string, error)
}

type Handlers struct {
   store Storage
}

func NewHandlers(store Storage) *Handlers {
   ...
   return &Handlers{
      store: store
   }
}

func (h *Handlers) someHandler(w http.ResponseWriter, r *http.Request) { 
   h.store.Create(...)
   ...
}


type Router struct {
   handlers *Handlers
}

func NewRouter(handlers Handlers) *Router {
	...
	r.Post("/", handlers.someHandler)
	r.Get("/id", handlers.someHandler)
	...
}
```

2024-07-05 02:35 UTC, capsulated commented on internal/handlers/metrics_handlers.go
> +            {{range .}}
Темплейт хотя бы в отдельный файлик перенести, а то найти в середине файла сложновато будет, если понадобится

2024-07-05 02:35 UTC, capsulated commented on internal/logger/logger.go
> +func InitLogger(logLevel string) error {
Я бы всё равно конструктор сделал (`func New(...) *Logger`) . Но в данном случае не критично, но с экземплярами работать проще

2024-07-05 02:35 UTC, capsulated commented on internal/logger/middleware.go
> +package logger
Так, миддлварю второю с логгером также в пакет миддлварей, а не в логгере. Получается в  middleware внедряется зависимость на логгер, вдруг мы логгер заменить захотим (а мидлварь оставить как есть)?

2024-07-05 02:35 UTC, capsulated commented on internal/models/metrics.go
> +	SystemMetrics struct {
Очень похоже на внтуренние поля `storage`... Я посмотрел в конструктор `NewMetricsStorage()`  - этот тип тут лишний. Можно просто:
```go
type MetricsStorage struct {
	sync.Mutex
	Counter: map[string]int64{},
	Gauge:   map[string]float64{},
)

func NewMetricsStorage() *MetricsStorage {
	return &MetricsStorage{
		Counter: map[string]int64{},
		Gauge:   map[string]float64{},
	}
}
```

2024-07-05 02:35 UTC, capsulated commented on internal/server/server.go
>  type MetricsServer struct {
Ну да, лучше `MetricsService`, `MetricsScrapper`, `MetricsHarvester`,  `MetricsCollector`, а то сбивает немного с толку именно `Server`

2024-07-05 02:35 UTC, capsulated commented on internal/server/server.go
> +		storage:         storage.NewMetricsStorage(),
Конструктор в конструкторе лучше не делать, иначе увеличивается связность объектов. Лучше на уровне выше создавать экземпляр хранилки и передать через интерфейс в конструктор. А конфиг - через указатель на тип `*Config` и его поля

2024-07-05 02:35 UTC, capsulated commented on internal/server/server.go
> +	SaveMetricsToFile(s.fileStoragePath, s.storage)
Вот отдельным сервисом бы реалиовать, с методами дампа в файл и загрузкой из фала. Не супер прям критично, но не очень удобно такие функции тестами покрывать и также связность выше

2024-07-05 02:35 UTC, capsulated commented on internal/server/services.go
> +package server
Да, я предлагаю сделать отдельный тип с методами

2024-07-05 02:35 UTC, capsulated commented on internal/server/services.go
> +func LoadMetricsFromFile(filename string, m *storage.MetricsStorage) error {
Указатель на хранилу можно не передавать. Необходимо в конструкторе хранилки вызавать метод загрузки из файла

2024-07-05 02:35 UTC, capsulated commented on internal/storage/contracts.go
> +type MetricsStorer interface {
Интерфейсы не в моделях, а в местах использования нужно стараться описывать

2024-07-05 02:35 UTC, capsulated commented on internal/storage/metrics_storage.go
> +type (
А зачем тут скобки, если единственный тип объявляем? Из-за скобок количество строк кода прибавляется и читабельность немного уменьшается

2024-07-05 02:35 UTC, capsulated commented on internal/storage/metrics_storage.go
> +		}
Ох, очень тяжелая для чтения конструкция. Необходимо как-то упрощать. Рекомендация [тут](https://go.dev/wiki/CodeReviewComments#indent-error-flow)

2024-07-05 16:05 UTC, eac0de commented on internal/storage/contracts.go
> +type MetricsStorer interface {
У меня сначала было в папке handlers, но потом он понадобился еще в другом месте и я его вынес в "общую" папку

2024-07-07 10:14 UTC, eac0de commented on cmd/server/main.go
> +	fmt.Println("StoreInterval:", serverConfig.StoreInterval)
Логгер инициализируется в методе server.Run()

2024-07-07 10:25 UTC, eac0de commented on internal/server/services.go
> +package server
Немного не понял

2024-07-07 10:25 UTC, eac0de commented on internal/server/services.go
> +package server
Не понял(

2024-07-09 17:17 UTC, capsulated approved these changes
Всё отлично, апрувлю! 🔥🦾

Пару минорных замечаний оставил, в слдеующем спринте можно пофиксить

2024-07-09 17:17 UTC, capsulated commented on internal/agent/agent.go
> +	go a.StartPoll(ctx)
🔥

2024-07-09 17:17 UTC, capsulated commented on internal/middlewares/compressor.go
> +package middlewares
Миддлвари тоже в `pkg` можно вынести

2024-07-09 17:17 UTC, capsulated commented on internal/storage/metrics_storage.go
> +		SystemMetrics: models.SystemMetrics{
Тут инициализация, можно как раз в конструкторе загружать из файла хранилку, передавая конфиг и проверив поле

2024-07-09 17:17 UTC, capsulated commented on main
Бинарник удалить из репо! )

2024-07-14 14:13 UTC, merged