Iter13
eac0de/getmetrics pull request #14
Opened 2024-07-18 12:27 UTC by eac0de

2024-07-21 23:36 UTC, capsulated requested changes
Добавил комментарии.

2024-07-21 23:36 UTC, capsulated commented on internal/handlers/db_handlers.go
> +func (dhs *databaseHandlerService) PingHandler() func(http.ResponseWriter, *http.Request) {
Можно общий интерфейс хранилки разделить с `pinger` и `closer` и проверять на соответствие интерфейсу. Хотя, дополнительный объект для разных конфигураций (использование БД/память) хорошая идея, но добавляет лишнего кода при добавлении новых хендлеров

2024-07-21 23:36 UTC, capsulated commented on internal/handlers/metrics_handlers.go
> +func RegisterMetricsHandlers(r chi.Router, storage storage.MetricsStorer) {
И запутаться сложнее, много регистраторов разных типов хендлеров. И нельзя сразу все эндпоинты посмотреть. Если есть предположение, что будут добавляться разные категории эндпоинтов, то скорее это надо разные микросервисы запускать, чем категории различные для хендлеров в одном создавать. Может я, конечно, не вижу идеи в целом, но не могу понять, какой это профит даёт? Пиши в комментарий, либо сразу небольшое описание (очень кратко, саму суть) этого паттерна в readme.md

2024-07-21 23:36 UTC, capsulated commented on internal/server/server.go
> +	db, err := storage.NewDatabaseSQL(ctx, s.conf.DatabaseDSN)
Тут всё в одной куче получилось: и назначение роутера и создание экземпляра хранилки, и причём именно на основе БД. Конструктор тут должен быть один - абстрактная фабрика, и внутри него уже в пакете хранилки, в зависимости от конфигов создаваться нужный тип хранилки и передеваться через интерфейс всем потребителям

2024-07-21 23:36 UTC, capsulated commented on internal/storage/contracts.go
> +type MetricsStorer interface {
Надо переносить к потребителю. Причём, если специального сервисного слоя нет для записи в БД, то потребителем будет пакет хендлеров. А если есть сервисный слой, который готовит и преобразует данные из хранилки - тогда потребителем будет именно этот слой, а пакете хендлеров о хранилке знать ничего не должен, только указатель или нтерфейс сервисного слоя.

2024-07-21 23:36 UTC, capsulated commented on internal/storage/database.go
> +	sqlDB *sql.DB
Может 'расширить' тогда  (как rextends в других ЯП)? Встраивание:
```go
type DB struct {
        *sql.DB
	mu    sync.Mutex
	...
}
```

2024-07-21 23:36 UTC, capsulated commented on internal/storage/database.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
Контекст лучше в параметр передавать и наследоваться от него, если нужно. Управлять контекстом часто требуется в месте вызова

2024-07-21 23:36 UTC, capsulated commented on internal/storage/database.go
> +	return db.sqlDB.Close()
Закрытие подключения к БД тоже должно быть с контекстом, есть там в библиотеке?

2024-07-21 23:36 UTC, capsulated commented on internal/storage/database.go
> +	case Gauge:
Вот всё это безобразие хорошо бы переместить на сервисный слой:  `NewMetricService(..., storage Storage) *NewMetricService {..}` с общими методами для манипуляции с хранением метрик: СохранитьМетрики(), ПолучитьМетрики() и тп. А на уровне БД максимально простые операции на увроне работы с БД (SELECT / UPDATE / INSETRT ...) и имена методов будут приближены к  именам операторов SQL: SelectAllMetrics, SelectMetricById, BatchMetrics и тп

2024-07-21 23:36 UTC, capsulated commented on internal/storage/database.go
> +func (db *DatabaseSQL) SaveMany(ctx context.Context, umList []*models.UnknownMetrics) ([]*models.Metrics, error) {
Немного непонятно: `[]*models.UnknownMetrics` и `[]*models.Metrics` для чего разные объекты? Может как-то при создании определять тип метрики? А две разных модели кажется лишним

2024-07-21 23:36 UTC, capsulated commented on internal/storage/metrics_storage.go
> +	if filename != "" {
Может просто указатель на весь конфиг передать? Или на поле конфига?  Просто `filename` не совсем явно

2024-07-22 09:48 UTC, eac0de commented on internal/handlers/db_handlers.go
> +func main() {
Извините, я это брал для примера, забыл удалить

2024-07-22 17:54 UTC, eac0de commented on internal/storage/database.go
> +	return db.sqlDB.Close()
Неа

2024-07-22 19:36 UTC, eac0de commented on cmd/server/main.go
> -	storage := storage.NewMetricsStorage()
Оставил создание storage в методе Run сервера, потому что в этом методе я выполняю storage.Close() И для того чтобы предусмотреть ситуацию что storage был создан но метод Run не был вызван, я оставил так. Тем более я считаю metricsService основным инстансом сервера

2024-07-23 06:37 UTC, eac0de commented on internal/handlers/metrics_handlers.go
> +func RegisterMetricsHandlers(r chi.Router, storage storage.MetricsStorer) {
Я работаю на питоне Джанго и Фастапи, там привычное дело создавать отдельные роутеры и в общем файле обьединять их

2024-07-24 17:50 UTC, capsulated approved these changes
Добавил комментарии. Есть ещё над чем работать. Замечания по структуре, они на логику не повлияют, автотесты прошли. Я апрувлю, но в след спринте нам надо обязательно навести порядок со всем этим: там вложенность объектов очень сильно "переплетена" между собой, надо исправлять (хранилка с БД, как главный претендент)

Давай в начале след спринта попробуй пофиксить то, что я добавил в комментах. А после созвонимся и я тебе в отдельной ветке подробнее напишу в коде в комментариях с примерами, в случае, если останутся замечания

2024-07-24 17:50 UTC, capsulated commented on cmd/server/main.go
> -	storage := storage.NewMetricsStorage()
Из запуска инициализацию точно надо убирать. Отдельно конструкторы с инициализацией, отдельно методы запуска/остановки. На уровне app (или cmd) необходимо инициализировать всё, если нет ошибок - уже запуск. Тогда уже на этапе инициализации часть ошибок будет предусмотрено. 

Если есть структура (тип), которая собирает и запускает всё приложение метрик, то лучше её описать в отдельном пакете `app` (или `internal/app`). А в cmd можно спарсить конфигурацию, передать конфиг конструктору приложения и запустить его.

Это уже не сервис, а именно приложение (app), и нейминг в таком случае надо изменить (MetrciServerApp или что-то подобное). А если `MetricsService` - это сервисный слой (к примеру, дополнительный слой между хендлерами и хранилкой), тогда нейминг лучше уточнить, что-то типа MetricsStorageService. С методами GetMetric, StoreMetric, StoreMetrics, GetMetricBy... А в пакете хранилки уже более низкоуровневые методы, типа SelectAllMetrics, UpdateMetric, InsertMetrcisBatch, UpdateMetrcisBatch и тп

Но кажется, что MetricsService это всё же app

2024-07-24 17:50 UTC, capsulated commented on internal/database/postgresql.go
> +	SQLPinger interface {
А к файловой хранилке можно же тоже пингер реализовать, с проверкой на существование файла

2024-07-24 17:50 UTC, capsulated commented on internal/database/postgresql.go
> +func execWithRetry(
Ох, как монструозно они выглядят в итоге))) Но штож, было в ТЗ. К своей базе не встречал ретраи, обычно добавляют к сторонним API или SaaS

2024-07-24 17:50 UTC, capsulated commented on internal/models/metrics.go
> +	MetricsMap struct {
Детали реализации (Map) фигурировать в нейминге не должны. Можно назвать типа MetricsDict или MetricsList

2024-07-24 17:50 UTC, capsulated commented on internal/handlers/metrics_handlers.go
> +	return func(w http.ResponseWriter, r *http.Request) {
можно уже не возвращать функцию

2024-07-24 17:50 UTC, capsulated commented on internal/routers/router.go
> +func (r *Router) AddMiddlewares() {
Можно и не выносить в отдельный метод

2024-07-24 17:50 UTC, capsulated commented on internal/routers/router.go
> +	r.Get("/", handlerService.ShowMetricsSummaryHandler())
Это всё в конструкторе делать удобнее. А конструктор для хендлеров лучше вызвать на уровне выше, где вызов RegisterMetricsHandlers, и передать указать на экземпляр хендлеров в конструктор роутера, Связность уменьшиться

2024-07-24 17:50 UTC, capsulated commented on internal/storage/db_storage.go
> +func NewDatabaseStorage(ctx context.Context, DSN string) (*databaseStorage, error) {
Так, а вот же структура для БД хранилки. А там где-то её методы отдельно "валяются" )) непорядок))

2024-07-24 17:50 UTC, capsulated commented on internal/storage/db_storage.go
> +	metric, err := database.SelectMetricFromDatabase(ctx, dbs.sqlDB, metricName, metricType)
А вот тут уже jxtym нехорошо, что используется переменная`database`. Это глобальная переменная? Должны же быть dbs.sqlDB.МетодПолученияЗаписиДанных(). Тогда у тебя хранилка - это `database`, а `databaseStorage` - это скорее как раз сервисный слой `MetricStrorageService`

2024-07-24 17:50 UTC, capsulated commented on internal/storage/db_storage.go
> +	return dbs.SaveBySQLModel(ctx, dbs.sqlDB, metric)
Вот это очень странно, 64 строка  (GetAll) 
```go
return database.SelectAllMetricsFromDatabase(ctx, dbs.sqlDB)
```
А тут 68 строка (Save):
```go
return dbs.SaveBySQLModel(ctx, dbs.sqlDB, metric)
```

Должно быть всё на основе `dbs`

2024-07-24 17:50 UTC, capsulated commented on internal/storage/db_storage.go
> +func (dbs *databaseStorage) MergeMetricsList(metricsList []models.Metrics) ([]models.Metrics, error) {
Этот метод не к хранилке относиться. Модно к модели его приделать

2024-07-24 17:50 UTC, capsulated commented on internal/storage/db_storage.go
> +				errList = append(errList, NewErrorWithHTTPStatus(fmt.Errorf("metric %s with type %s must have filled value", metric.ID, models.Gauge), http.StatusBadRequest))
На уровне хранилки не должно быть ошибок с уровня HTTP, только SQL. Ошибки HTTP должны быть на уровне хендлеров

2024-07-24 17:50 UTC, capsulated commented on internal/storage/file_storage.go
> +type fileStorage struct {
Тип тоже глобальный, так как конструктор глобальный

2024-07-24 17:50 UTC, capsulated commented on internal/storage/file_storage.go
> +	memoryStorage := NewMemoryStorage()
Новый файловая хранилка создаёт хранилку в памяти? Может просто для хранилки в памяти добавить воркер для работы с файлами и дергать его методы, если в конфигах выставлены флаги? А то слишком высокая связность, хранилка в  памяти "гвоздями прибита" к файловой хранилке

2024-07-24 17:50 UTC, capsulated commented on internal/storage/file_storage.go
> +	go fs.StartSavingMetrics(ctx)
Это нужно на уровне app/cmd запускать, но не в конструкторе. Инициализацию и запуск всегда надо отделять, это разные области ответсвенности

2024-07-24 18:31 UTC, eac0de commented on internal/handlers/metrics_handlers.go
> +	return func(w http.ResponseWriter, r *http.Request) {
Не понимаю) Знаю что можно использовать саму функцию вместо хендлера, ты про это?

2024-07-24 20:50 UTC, merged

2024-07-25 09:44 UTC, eac0de commented on internal/storage/file_storage.go
> +	memoryStorage := NewMemoryStorage()
Я встроил хранилку в памяти в хранилку в файле, потому что хранилка в памяти добавляет только некоторые методы для работы с файлами, то есть файловая хранилка это просто дополнение к хранилке в памяти. Получается она не гвоздями прибита а дополняет уже существующую хранилку

2024-07-25 09:49 UTC, eac0de commented on internal/storage/file_storage.go
> +	go fs.StartSavingMetrics(ctx)
То есть мне инизиализацию файловой хранилки нужно добавлять в инициализацию приложения и добавлять поле в структуру приложения, чтобы потом проверять есть ли файловая хранилка, и вызывать ее методы? Разве не получиться каша?

2024-07-25 09:53 UTC, eac0de commented on internal/storage/db_storage.go
> +				errList = append(errList, NewErrorWithHTTPStatus(fmt.Errorf("metric %s with type %s must have filled value", metric.ID, models.Gauge), http.StatusBadRequest))
Тогда я не смогу возвращать некоторые коды, которые описаны в задании, например если у меня вернулась ошибка при сохранении что не указано имя мне нужно вернуть 404 ошибку(как описано в задании), а другие 400.
Придется создавать ошибку просто с кодом ошибки(которые я сам определю) и опять же проверять какой код ошибки соответсвует какому HTTP статусу. Опять получиться больше кода

2024-07-25 09:59 UTC, eac0de commented on internal/storage/db_storage.go
> +	return dbs.SaveBySQLModel(ctx, dbs.sqlDB, metric)
В dbs.SaveBySQLModel(ctx, dbs.sqlDB, metric) также используются методы из пакета database. Я сделал методы в database которые принимают SQLModel чтобы передавать туда либо sql.DB либо TX, чтобы не определять отдельные методы для каждого с одинаковыми запросами. Могу сделать структуру и пихнуть туда эти методы? Или как сделать?

2024-07-25 10:00 UTC, eac0de commented on internal/storage/db_storage.go
> +	metric, err := database.SelectMetricFromDatabase(ctx, dbs.sqlDB, metricName, metricType)
database это пакет, нужно создать структуру и пихнуть туда эти методы? Или по другому

2024-07-25 10:01 UTC, eac0de commented on internal/storage/db_storage.go
> +func NewDatabaseStorage(ctx context.Context, DSN string) (*databaseStorage, error) {
Это именно хранилка метрик, а там отдельные методы для работы с постгрескл. Это как раз сервисный слой между приложением и работой с базой данных

2024-07-25 10:06 UTC, eac0de commented on internal/database/postgresql.go
> +	SQLPinger interface {
В задаче было - "Добавьте в сервер хендлер GET /ping, который при запросе проверяет соединение с базой данных. "

2024-07-25 10:14 UTC, eac0de commented on cmd/server/main.go
> -	storage := storage.NewMetricsStorage()
Нужно обьяснить(